Adicionando ambiente de desenvolvimento
PHPMT/PseudoORM pull request #29
Opened 2016-11-03 05:01 UTC by jackmakiyama

Ambiente de desenvolvimento padronizado com o Docker e orquestrado com o
docker-compose, contendo: PHP7, Postgres 9.6 e nginx.

2016-11-03 05:37 UTC, jackmakiyama commented
Para instalar as dependências do composer:

```
$ make composer.install
```

2016-11-03 15:41 UTC, jackmakiyama commented
@EvandroMohr @f0ntana @enieber review please.

2016-11-03 16:21 UTC, enieber reviewed
ficou legal essa parte de rodar o composer com o make... mas tem que instalar alguma coisa para rodar esse makefiel ?

2016-11-03 16:21 UTC, enieber commented on docker-compose.yml
> +version: '2'
o que seria esse version 2? tentei rodar no meu docker-compose mas deu erro

2016-11-03 17:41 UTC, jackmakiyama commented on docker-compose.yml
> +version: '2'
é a versão do cocker.composer.yml, [veja mais aqui](https://medium.com/@giorgioto/docker-compose-yml-from-v1-to-v2-3c0f8bb7a48e#.5t8zm9tvq).

2016-11-03 17:42 UTC, jackmakiyama commented
> ficou legal essa parte de rodar o composer com o make... mas tem que instalar alguma coisa para rodar esse makefiel ?

Rapaz, creio que não precisa de nada, a maioria dos unix-like tem, na duvida: `make --version` no terminal.

2016-11-03 17:43 UTC, jackmakiyama commented on docker-compose.yml
> +version: '2'
Atualize seu Docker se puder.

2016-11-03 18:15 UTC, enieber approved these changes

2016-11-10 06:44 UTC, enieber commented
cara ficou legal, mas não consegui testar por causa do tamanho, minha internet não ajuda..

2016-11-12 14:42 UTC, jackmakiyama commented
> cara ficou legal, mas não consegui testar por causa do tamanho, minha internet não ajuda..

😢

2016-11-17 16:25 UTC, enieber commented
@jackmakiyama sera que da para pegar imagens menores para facilitar a portabilidade do projeto?

2016-11-23 12:15 UTC, EvandroMohr requested changes
Alterar portas padrão para evitar conflito de ambiente

2016-11-23 12:15 UTC, EvandroMohr commented on docker-compose.yml
> +          - "5432:5432"
Sugiro mudar a porta que ele sobe. pra não dar conflito caso já tenha outra instancia do postgresql rodando

2016-11-23 12:15 UTC, EvandroMohr commented on docker-compose.yml
> +            - "80:80"
mudar porta padrão, para evitar conflito com outras instâncias

2016-11-23 22:33 UTC, EvandroMohr approved these changes

2016-11-23 22:34 UTC, merged